language: go

sudo: false

go:
  - 1.6.2
  - tip

before_install:
  - go get -v github.com/alecthomas/gometalinter && gometalinter --install

install: go get -v -d -t ./...

script:
  - go test -v -cover ./...
  - gometalinter -E gofmt -D gotype -D vetshadow -D dupl -D goconst -D interfacer -D gocyclo --tests --deadline=10m ./...
