language: go

go:
  - 1.4
  - tip

before_install:
  - export PATH=$PATH:$GOROOT/bin:/home/travis/gopath/bin #ugly hack
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v golang.org/x/tools/cmd/vet
  - go get -v github.com/golang/lint/golint

install: go get -v -t ./...

script:
  - go test -v -cover -short ./...
  - golint ./...
