language: go

go:
  - 1.3
  - tip

before_install:
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v code.google.com/p/go.tools/cmd/goimports
  - go get -v github.com/golang/lint/golint
  - export PATH=$PATH:/home/travis/gopath/bin #ugly hack

script:
  - go test -v -cover -short ./...
  - golint .
  - goimports -l .
