language: go

sudo: false

go:
  - 1.8
  - tip

install: go get -v -d -t ./...

script:
  - go test -v -cover ./...
  - >
    go get -v github.com/alecthomas/gometalinter &&
    gometalinter --install &&
    gometalinter -E gofmt -D gotype -D vetshadow -D dupl -D goconst -D interfacer --tests --deadline=10m ./...
