language: go

go:
  - 1.3.1
  - tip

before_install:
  - export PATH=$PATH:$GOROOT/bin:/home/travis/gopath/bin #ugly hack
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go get -v code.google.com/p/go.tools/cmd/goimports
  - go get -v github.com/golang/lint/golint

script:
  - go test -v -cover -short ./...
  - golint .
  - goimports -l .
