language: go

sudo: false

go:
  - 1.5.3
  - tip

before_install:
  - go get -v github.com/golang/lint/golint

install: go get -v -t ./...

script:
  - go test -v -cover ./...
  - gofmt -d .
  - go tool vet .
  - golint ./...
